name: CI Test
on:
  push:
    branches: ['feat/#94']
  pull_request:
    branches: ['feat/#94']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 코드 작업환경으로 가져오기
      - uses: actions/checkout@v3
      # Node 설치
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      # yarn install
      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command
      # yarn build
      - name: Run build
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Deploy to S3
        run: aws s3 sync ./build s3://dongnemashil --profile=${{secrets.AWS_PROFILE_NAME}}
